export const ACTION_ENTER_CHAT = "ENTER_CHAT";
export const ACTION_ENTER_CHAT_SUCCESS = "ENTER_CHAT_SUCCESS";
export const ACTION_SEND_CHAT_MESSAGE = "SEND_CHAT_MESSAGE";
export const ACTION_RECEIVED_CHAT_MESSAGE = "RECEIVED_CHAT_MESSAGE";

export const URL_SOCKET = "http://localhost:8000";